image: "python:3.7"

stages:
  - test

test:
  stage: test
  script:
    - export DJANGO_SETTINGS_MODULE=config.settings.tests
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip default-libmysqlclient-dev
    - pip3 install -r requirements/general.txt
    - python3 --version
    - python3 manage.py test
    - pip3 install -r requirements/development.txt
    - pylint --rcfile=.pylintrc --load-plugins pylint_django apps
