# Generated by Django 3.0.5 on 2020-12-04 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_additionaloptions', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_additionaloptions', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Дополнительная опция',
                'verbose_name_plural': 'Дополнительные опции',
                'db_table': 'vehicle_additional_options',
            },
        ),
        migrations.CreateModel(
            name='BodyColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bodycolors', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bodycolors', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Цвет кузова',
                'verbose_name_plural': 'Цвета кузова',
                'db_table': 'vehicle_body_colors',
            },
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bodytypes', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bodytypes', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
                'db_table': 'vehicle_body_types',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_brands', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'vehicle_brands',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fueltypes', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fueltypes', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Вид топлива',
                'verbose_name_plural': 'Виды топлива',
                'db_table': 'vehicle_fuel_types',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_models', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
                'db_table': 'vehicle_models',
            },
        ),
        migrations.CreateModel(
            name='VehicleAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('source', models.CharField(choices=[('olx', 'olx.uz'), ('avtoelon', 'avtoelon.uz')], max_length=20, verbose_name='Источник объявления')),
                ('title', models.TextField(verbose_name='Заголовок объяления')),
                ('description', models.TextField(verbose_name='Заголовок объяления')),
                ('url', models.URLField(verbose_name='URL объявления')),
                ('manufactured_year', models.SmallIntegerField(verbose_name='Год выпуска')),
                ('number_of_owners', models.SmallIntegerField(verbose_name='Количество хозяев')),
                ('transmission_type', models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'Механическая'), ('other', 'Другое')], max_length=20, verbose_name='Трансмиссия')),
                ('condition', models.CharField(choices=[('perfect', 'Отличное'), ('good', 'Хорошее'), ('mediocre', 'Среднее'), ('needs_repairs', 'Требует ремонта')], max_length=20, verbose_name='Состояние')),
                ('engine_capacity', models.SmallIntegerField(verbose_name='Объем двигателя (sm3)')),
                ('driven_km', models.SmallIntegerField(verbose_name='Пробег (км)')),
                ('price_usd', models.BigIntegerField(verbose_name='Цена USD')),
                ('price_uzs', models.BigIntegerField(verbose_name='Цена UZS')),
                ('additional_options', models.ManyToManyField(related_name='ads', to='vehicle.AdditionalOption', verbose_name='Дополнительные опции')),
                ('body_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.BodyColor', verbose_name='Цвет кузова')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.BodyType', verbose_name='Тип кузова')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Brand', verbose_name='Производитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicleads', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('fuel_types', models.ManyToManyField(related_name='ads', to='vehicle.FuelType', verbose_name='Виды топлива')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Model', verbose_name='Модель')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vehicleads', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Объявление о продаже машины',
                'verbose_name_plural': 'Объявления о продаже машин',
                'db_table': 'vehicle_ads',
            },
        ),
    ]
