# Generated by Django 3.0.5 on 2020-12-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycolor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание объяления'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='driven_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег (км)'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='engine_capacity',
            field=models.PositiveIntegerField(verbose_name='Объем двигателя (sm3)'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='price_usd',
            field=models.BigIntegerField(default=0, verbose_name='Цена USD'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='price_uzs',
            field=models.BigIntegerField(default=0, verbose_name='Цена UZS'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='source',
            field=models.CharField(choices=[('olx', 'olx.uz'), ('avtoelon', 'avtoelon.uz')], default='olx', max_length=20, verbose_name='Источник объявления'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='url',
            field=models.URLField(db_index=True, verbose_name='URL объявления'),
        ),
    ]
