# Generated by Django 3.0.5 on 2020-12-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_model_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclead',
            name='fuel_types',
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='fuel_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.FuelType', verbose_name='Виды топлива'),
            preserve_default=False,
        ),
    ]
