# Generated by Django 3.0.5 on 2020-12-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20201205_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclead',
            name='condition',
            field=models.CharField(choices=[('perfect', 'Отличное'), ('good', 'Хорошее'), ('mediocre', 'Среднее'), ('needs_repairs', 'Требует ремонта')], max_length=20, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='transmission_type',
            field=models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'Механическая'), ('other', 'Другая')], max_length=20, null=True, verbose_name='Трансмиссия'),
        ),
    ]
