# Generated by Django 3.0.5 on 2020-12-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
        ('vehicle', '0005_auto_20201205_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclead',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference.Area', verbose_name='Город/Район'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclead',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference.Region', verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
