# Generated by Django 3.0.5 on 2020-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20201205_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloption',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vehiclead',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL объявления'),
        ),
    ]
