# Generated by Django 3.0.5 on 2020-12-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20201205_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Слова для игнорирования объявления',
                'verbose_name_plural': 'Слова для игнорирования объявления',
                'db_table': 'vehicle_stop_words',
            },
        ),
    ]
