CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

BROKER_POOL_LIMIT = 10
BROKER_CONNECTION_TIMEOUT = 10

CELERY_SEND_EVENTS = True
CELERY_TASK_RESULT_EXPIRES = 3 * 86400
CELERY_IGNORE_RESULT = True
CELERY_ACKS_LATE = True
